/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {
}
declare global {
    // const createApp: typeof import('vue')['createApp']
    // const defineComponent: typeof import('vue')['defineComponent']
    // const getCurrentInstance: typeof import('vue')['getCurrentInstance']
    // const onActivated: typeof import('vue')['onActivated']
    // const onBeforeMount: typeof import('vue')['onBeforeMount']
    // const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
    // const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
    // const onDeactivated: typeof import('vue')['onDeactivated']
    // const onErrorCaptured: typeof import('vue')['onErrorCaptured']
    // const onMounted: typeof import('vue')['onMounted']
    // const onRenderTracked: typeof import('vue')['onRenderTracked']
    // const onRenderTriggered: typeof import('vue')['onRenderTriggered']
    // const onUnmounted: typeof import('vue')['onUnmounted']
    // const onUpdated: typeof import('vue')['onUpdated']
    // const provide: typeof import('vue')['provide']
    // const reactive: typeof import('vue').ref
    // const readonly: typeof import('vue')['readonly']
    // const ref: typeof import('vue').ref
    // const useRoute: typeof import('vue-router')['useRoute']
    // const useRouter: typeof import('vue-router')['useRouter']
    // const watch: typeof import('vue')['watch']
    // const watchEffect: typeof import('vue')['watchEffect']
}
