/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElAside: (typeof import('element-plus/es'))['ElAside'];
        ElAvatar: (typeof import('element-plus/es'))['ElAvatar'];
        ElBacktop: (typeof import('element-plus/es'))['ElBacktop'];
        ElBadge: (typeof import('element-plus/es'))['ElBadge'];
        ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb'];
        ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem'];
        ElButton: (typeof import('element-plus/es'))['ElButton'];
        ElCard: (typeof import('element-plus/es'))['ElCard'];
        ElCol: (typeof import('element-plus/es'))['ElCol'];
        ElColorPicker: (typeof import('element-plus/es'))['ElColorPicker'];
        ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
        ElContainer: (typeof import('element-plus/es'))['ElContainer'];
        ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker'];
        ElDialog: (typeof import('element-plus/es'))['ElDialog'];
        ElDivider: (typeof import('element-plus/es'))['ElDivider'];
        ElDrawer: (typeof import('element-plus/es'))['ElDrawer'];
        ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
        ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
        ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu'];
        ElForm: (typeof import('element-plus/es'))['ElForm'];
        ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
        ElHeader: (typeof import('element-plus/es'))['ElHeader'];
        ElIcon: (typeof import('element-plus/es'))['ElIcon'];
        ElImage: (typeof import('element-plus/es'))['ElImage'];
        ElInput: (typeof import('element-plus/es'))['ElInput'];
        ElLink: (typeof import('element-plus/es'))['ElLink'];
        ElMain: (typeof import('element-plus/es'))['ElMain'];
        ElMenu: (typeof import('element-plus/es'))['ElMenu'];
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
        ElMessage: (typeof import('element-plus/es'))['ElMessage'];
        ElMessageBox: (typeof import('element-plus/es'))['ElMessageBox'];
        ElOption: (typeof import('element-plus/es'))['ElOption'];
        ElPagination: (typeof import('element-plus/es'))['ElPagination'];
        ElProgress: (typeof import('element-plus/es'))['ElProgress'];
        ElRow: (typeof import('element-plus/es'))['ElRow'];
        ElScrollbar: (typeof import('element-plus/es'))['ElScrollbar'];
        ElSelect: (typeof import('element-plus/es'))['ElSelect'];
        ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu'];
        ElSwitch: (typeof import('element-plus/es'))['ElSwitch'];
        ElTable: (typeof import('element-plus/es'))['ElTable'];
        ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
        ElTabPane: (typeof import('element-plus/es'))['ElTabPane'];
        ElTabs: (typeof import('element-plus/es'))['ElTabs'];
        ElTimeline: (typeof import('element-plus/es'))['ElTimeline'];
        ElTimelineItem: (typeof import('element-plus/es'))['ElTimelineItem'];
        ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
        ElTree: (typeof import('element-plus/es'))['ElTree'];
        IEpClose: (typeof import('~icons/ep/close'))['default'];
        IEpElementPlus: (typeof import('~icons/ep/element-plus'))['default'];
        IEpSetting: (typeof import('~icons/ep/setting'))['default'];
        IEpUser: (typeof import('~icons/ep/user'))['default'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
    }
}
