/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        ElAside: (typeof import('element-plus/es'))['ElAside'];
        ElButton: (typeof import('element-plus/es'))['ElButton'];
        ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
        ElContainer: (typeof import('element-plus/es'))['ElContainer'];
        ElDialog: (typeof import('element-plus/es'))['ElDialog'];
        ElForm: (typeof import('element-plus/es'))['ElForm'];
        ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
        ElHeader: (typeof import('element-plus/es'))['ElHeader'];
        ElInput: (typeof import('element-plus/es'))['ElInput'];
        ElMain: (typeof import('element-plus/es'))['ElMain'];
        ElMenu: (typeof import('element-plus/es'))['ElMenu'];
        ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
        ElOption: (typeof import('element-plus/es'))['ElOption'];
        ElPagination: (typeof import('element-plus/es'))['ElPagination'];
        ElSelect: (typeof import('element-plus/es'))['ElSelect'];
        ElTable: (typeof import('element-plus/es'))['ElTable'];
        ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
        ElTree: (typeof import('element-plus/es'))['ElTree'];
        RouterLink: (typeof import('vue-router'))['RouterLink'];
        RouterView: (typeof import('vue-router'))['RouterView'];
    }
}
